from src.prompts.analyse_sentiment import analyse_prompt
from src.components.schemas import State, Report, AssetInformation
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.prompts import MessagesPlaceholder, ChatPromptTemplate
from langchain_core.messages import AIMessage
from typing_extensions import List
from langchain_core.documents import Document

def format_report(report : Report, retrieved_news: List[Document]) -> AIMessage:
    """
    Format the report structured output report into an AIMessage

    Args:
        report (Report): Market sentiment report generated by the LLM
        retrieved_news (List[Document]): List of retrieved news for the given trading asset
    Returns:
        AIMessage: An AI message of the formatted report
    """
    formatted_report = f"""
    # Report
    {report.report}

    **Curent Market Sentiment**: {report.current_sentiment}
    **Future Market Sentiment**: {report.future_sentiment}

    
    # Cited News Articles
    {
        "\n\n".join([
            f"""========== News Article {i} ==========
            News Title: {doc.metadata['title']}
            News URL: {doc.metadata['link'] if doc.metadata['link'] != '' else '[Link Unavailable]'}
            News Content: {doc.page_content.strip()}""" 
            for i,doc in enumerate(retrieved_news) if i in report.citations
        ])
    }
    """
    return AIMessage(content = formatted_report)

def analyse_market_sentiment(state : State, model : BaseChatModel , asset_information : AssetInformation) -> State:
    """
    Analyzes market sentiment based on provided news articles and generates a structured report.

    Args:
        state (State): The current pipeline state.
        model (BaseChatModel): The language model used for generating the sentiment analysis report.
        asset_information (AssetInformation): Information about the trading asset.
    Returns:
        State: An updated state of the graph."""
    
    # Retrieve the formatted news articles from the state
    formatted_news = state.formatted_news
    analyse_pt = ChatPromptTemplate(
        [
            ('system', analyse_prompt),
            MessagesPlaceholder('messages')
        ]
    )

    # Create a prompt template for the sentiment analysis
    report_chain = analyse_pt | model.with_structured_output(Report)
    # Invoke the model to generate the sentiment report
    report = report_chain.invoke(
        {
            "symbol_alias" : asset_information.symbol_alias, 
            "formatted_news" : formatted_news,
            "messages" : state.messages
        }
    )

    return {"messages" : [format_report(report, state.retrieved_news)], "report" : report}